version: '3.9'
services:
   elasticsearch:
      container_name: els
      image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
      ports:
         - 9200:9200
      volumes:
         - elasticsearch-data:/usr/share/elasticsearch/data
      environment:
           - xpack.security.enabled=false
           - discovery.type=single-node
           - ES_JAVA_OPTS=-Xms512m -Xmx512m
      networks:
         - elastic
   kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:8.15.0
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch
      environment:
        - ELASTICSEARCH_HOSTS=${ELA_HOST}
      networks:
        - elastic
   rabbitmq:
      container_name: rabbitmq
      image: rabbitmq:3-management
      ports:
        - 5672:5672
        - 15672:15672
      networks:
        - elastic
   redis:
      container_name: redis
      image: redis:latest
      ports:
         - 6379:6379
      networks:
         - elastic
   chatgroup-server:
      container_name: web-server
      image: chatgroup-server:version-1
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 5000:80 
      depends_on:
          - elasticsearch
          - rabbitmq
          - redis
      networks:
          - elastic
      environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - ELASTICSEARCH_URL=http://elasticsearch:9200
          - RABBITMQ_HOST=rabbitmq
          - REDIS_HOST=redis

networks:
   elastic:
       driver: bridge
volumes:
   elasticsearch-data:
